### ISSUE TITLE
SCA check 5035 about the SSH protocol is wrong

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-ruleset#383]
Here is the issued check:

https://github.com/wazuh/wazuh-ruleset/blob/48eae91b5c00e7dcbb5d1abbb5c1968aaacc6764/sca/debian/cis_debian_linux_rcl.yml#L475

```
- id: 5035
   title: "Ensure SSH Protocol is set to 2"
   description: "Older versions of SSH support two different and incompatible protocols: SSH1 and SSH2. SSH1 was the original protocol and was subject to security issues. SSH2 is more advanced and secure."
   rationale: "SSH v1 suffers from insecurities that do not affect SSH v2."
   remediation: "Edit the /etc/ssh/sshd_config file to set the parameter as follows: Protocol 2"
   compliance:
    - cis_csc: "14.4"
    - cis: "5.2.4"
    - pci_dss: "4.1"
   condition: any
   rules:
     - 'f:/etc/ssh/sshd_config -> IN !r:^# && r:Protocol\.+2;'
```

As the current logic works, it is looking for the line `Protocol 2` to determine a "fail" result.

The same check in other policies are correct: 
https://github.com/wazuh/wazuh-ruleset/blob/48eae91b5c00e7dcbb5d1abbb5c1968aaacc6764/sca/debian/cis_debianlinux7-8_L1_rcl.yml#L923
